const playlistActionTypes = {
  FETCH_DETAIL_INFORMATION_SUCCESS: 'FETCH_DETAIL_INFORMATION_SUCCESS',
  FETCH_LIST_INFORMATION_SUCCESS: 'FETCH_LIST_INFORMATION_SUCCESS',
  ADD_LIKED_SONG: 'ADD_LIKED_SONG',
  DELETE_LIKED_SONG: 'DELETE_LIKED_SONG'
};

export default playlistActionTypes;
